version: "3.9"

volumes:
  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      device: /home/zkotbi/data/wordpress
      o: bind
      type: none

  mariadb:
    name: mariadb
    driver: local
    driver_opts:
      device: /home/zkotbi/data/mariadb
      o: bind
      type: none

networks:
  inception:
    name: inception
services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx/.
    image: nginx:1337
    ports:
      - "443:443"
    depends_on:
      - wordpress
    volumes:
      - wordpress:/var/www/html
    networks:
      - inception
    env_file:
      - .env
    restart: always
  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress/.
    image: wordpress:1337
    depends_on:
      - mariadb
    volumes:
      - wordpress:/var/www/html
    networks:
      - inception
    env_file:
      - .env
    restart: always
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb/.
    image: mariadb:1337
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - inception
    env_file:
      - .env
    restart: always
  static_site:
    container_name: static_site
    build: ./requirements/bonus/static_site/.
    image: static_site:1.1
    ports:
      - "8000:4000"
    networks:
      - inception
    restart: always
  adminer:
    container_name: adminer
    build: ./requirements/bonus/adminer/.
    image: adminer:1337
    ports:
      - "8001:80"
    networks:
      - inception
    restart: always
  cadvisor:
    container_name: cadvisor
    build: ./requirements/bonus/cadvisor/.
    image: cadvisor:1.1
    ports:
      - "8002:8080"
    networks:
      - inception
    restart: always
